### ISSUE TITLE
FOQUS fails to install on Apple M1/ARM platforms

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#1100]
In particular, it's the PyQt5 that is the problem, there is no pip package for that architecture.  There is a PyQt6 package, but then FOQUS won't work with it.

Rosetta might be a work around for those on the M1/ARM chips.

**Comment by kbuma** [comment]
This appears to be due to there not being a wheel for this architecture thus requiring it to be compiled from source. Compiling from source fails because:
1) If you do not have qmake in you path it cannot build the package. To remedy this you can install Qt5 and add qmake to your path (e.g. using homebrew)
2) The build process for PyQt 5 has an interactive prompt that requires you to accept the license. This does not interact well with pip and causes the process to hang. (if you run pip in verbose mode you will see this)

My solution was to download and install PyQt based on the "Building and Installing from Source" instructions from https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html. Once that was done I could follow the normal instructions for installing FOQUS.

**Comment by kbuma** [comment]
@ksbeattie It looks like @bpaul4 has suggested a simpler solution in
https://github.com/CCSI-Toolset/FOQUS/discussions/1146
We should update our documentation with that.

I've verified that that works on my machine.

**Comment by bpaul4** [comment]
@eslickj identified the fix, and I agree it would be useful to update the documentation. According to the installation page we officially support Python 3.7 to 3.9, and our ARM fix uses 3.10. We should update the documentation if we do support 3.10 now.

**Comment by lbianchi-lbl** [comment]
This is great, thanks all for working on testing and documenting this.

Just adding a couple of items:

- [ ] Try if `python=3.10` is a requirement, or things also work with 3.8 and 3.9
- [ ] Run the complete test suite, including the GUI tests (@lbianchi-lbl to provide a command)

**Comment by kbuma** [comment]
verified that instructions from https://github.com/CCSI-Toolset/FOQUS/discussions/1146 work with 3.8

**Comment by lbianchi-lbl** [comment]
@kbuma I've created a wiki page on how to run GUI tests locally: https://github.com/CCSI-Toolset/FOQUS/wiki/howto-gui-tests. Let me know if you run into any errors so we can update those steps for future reference.

**Comment by kbuma** [comment]
Looks like the tests passed.

[test-results.txt](https://github.com/CCSI-Toolset/FOQUS/files/11739827/test-results.txt)

@lbianchi-lbl just as an FYI psuade-lite will not install via conda on Apple ARM as there's currently no osx-arm64 version of the conda package. I built it from source from https://github.com/LLNL/psuade-lite and used that install for the tests.
