### ISSUE TITLE
Windows 2022 Server/Aspen v14: phase 1 - SimSinter

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1156]
Deploy, test, investigate using FOQUS with this updated platform

- Windows 2022 Server
- Aspen v14

As a first step build SimSinter on this platform and make necessary updates to software.

- [x] create oVirt template base with Windows 2022 Server: install with oVirt drivers, oVirt agent and LBL security requirements
- [x] create oVirt template with all platform requirements: base Windows 2022 Server template, SQL Server 2019 Express, Office 2021, Aspen v14
- [x] update SimSinter project to build on this platform with Visual Studio 2022
- [x] ensure SimSinter regression tests work on new platform
- [x] create SimSinter installer and test on this platform
- [x] test SimSinter installer compatibility with legacy platforms

**Comment by kbuma** [comment]
Need to make a decision on the following regression tests are failing on the new platform:

- [ ] SinterDynamicACMTest_1 due to failure to load snapshot (looks like this may be a COM issue as am able to load the snapshot interactively using the test file in ACM)
- [ ] SinterDynamicACMTest_2 due to failure to load snapshot (looks like this may be a COM issue as am able to load the snapshot interactively using the test file in ACM)
- [ ] SinterGPROMSTest due to not having access to the gPROMS executable
- [ ] UnitTest1 due to following reported error: Exception while running simulation: ERROR: Input file defined units degF and Sinter Config file defined unit degC are not compatiable!

**Comment by kbuma** [comment]
Install completes fines but SinterGUIConfig has issues loading classes from the UC2 library - need to debug the issue.

**Comment by kbuma** [comment]
The unit conversion library from SimSinter makes building and packaging the project very error prone and time consuming. Based on initial discussions with the community the unit conversion functionality is not a heavily used feature. Thus, we have decided to remove this feature from SimSinter. This will result in the following change in behavior of SimSinter.

**Current Behavior**
When the input contains a variable that is compatible with the application model definition, e.g. degC input and degF app, SimSinter converts the value to degF and provides that along with degF to the app.

**New Behavior**
When the input contains a variable that is compatible with the application model definition, e.g. degC input and degF app, SimSinter returns an error due to the units not being a match.

**Comment by kbuma** [comment]
Our developers (and our community?) do not have access to gPROMS. We will not continue to support this feature unless the community deems it high priority. For the moment we have left the codebase as is, only removing the SinterGPROMSTest from the regression test suite. We will create a separate issue for the full removal.

**Comment by kbuma** [comment]
Created installer and verified that Opening a Simulation with SinterConfigGUI from the Installation Manual works as expected on following platforms:

- Windows Server 2022, Aspen v14
- Windows 11, Aspen v12
