### ISSUE TITLE
FOQUS OUU failures: how to handle?

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#326]
Discussion (motivated by #321  ) on what types of errors are re-submittable and which ones are not.  Can the sample size be automatically reduced, throwing out a few jobs that failed?

@CSRussell2319 will follow up with colleagues on viability of throwing failed jobs out or methods for confirming we have an accurate distribution.

**Comment by CSRussell2319** [comment]
The issue occurs when running OUU. The problem is that the current implementation will toss out all completed runs in an iteration if even one of them results in a failure. This would waste a considerable amount of CPU cycles/time. The goal of this issue is to come up with a way to use the successful runs and possibly generate more runs on a case-by-case basis when there are failures. I had an email exchange with @candcook and she has mentioned that this is possible, but there are changes that would need to happen under the hood to support it. I was planning on discussing what was said in more detail at the next dev meeting.

**Comment by sotorrio1** [comment]
Got it. Thanks for clarifying, @CSRussell2319

**Comment by CSRussell2319** [comment]
The main issue here (runs failing and causing an entire iteration to fail) can be solved using statistical techniques that would create new samples based on the results from the previous run. This does not guarantee success, but it reduces computation time while trying to maintain a space-filling design. The issue itself isn't a bug, but rather a self-check to ensure that the samples are actually space-filling.

Consistent convergence errors could indicate issues with the bounds set on the initial parameters and could happen even if the new statistical method was introduced. It requires user input to resolve. Following issue #232 there should be, at a minimum, an error notification that informs the user why optimization was cancelled by FOQUS (too many failed iterations), where the results are stored (csv file in working directory), what needs to be done to fix the issue (adjust the boundaries for the selected parameters), and how the data will inform boundary adjustment. 

As a long term goal we should consider incorporating a new sampling method that can take historical runs and add new samples intelligently to maintain a space-filling design. I don't think anyone currently has time for this so it will probably not happen.

**Comment by ksbeattie** [comment]
Given that the long term solution, described above by @CSRussell2319, isn't going to be implemented anytime soon, we're lowing the priority on this and removing it from the Feb release board.

**Comment by ksbeattie** [comment]
This is a subset of #676

**Comment by boverhof** [comment]
no progress, outdated
