### ISSUE TITLE
Eliminate FOQUS Direct TurbineLite DB Acess?

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#365]
I'm having some trouble smoothly installing adodbapi, which go me thinking about whether it is a good idea for FOQUS to do things by directly interacting with the TurbineLite database.  Originally I think we did it because it was a quick way to allow FOQUS more control over starting and stopping simulations.  Would it be better to add some more stuff to the Turbines rest api instead?

**Comment by ksbeattie** [comment]
@boverhof can you speak to this?

**Comment by boverhof** [comment]
## issue 1: read/write/update to Database
A first start would be to document all the places in FOQUS where direct DB access is being made, secondly specify the REST API extension that are required to support this access, and evaluate how difficult this is to accomplish.  

## issue 2:  simulation process management 
I think this goes beyond the "API", however, starting and stopping simulations also involves forking processes and managing them.  Currently FOQUS manages Turbine processes and uses Turbine Database solely for managing status.  The "Windows Services" for ACM/AspenPlus are no longer used because a greater degree of control was required for flowsheet execution.

## evaluation
If issue 1 can be addressed independently of "issue 2" I think it makes sense to move away from adodbapi.  If both have to be addressed together I think it's a large undertaking.

**Comment by ksbeattie** [comment]
@eslickj says this is now more of a long-term goal.  Lowering priority.

**Comment by fsoepyan** [comment]
- I no longer run into the issue with adodbapi.
- Would anyone object if we close this issue? (I am moving this issue to "High" priority in the project board.)

**Comment by eslickj** [comment]
@fsoepyan, long term I still think it's better not to have FOQUS working directly in Turbine's database.  I think we should keep this.  I'm pretty busy, but I'll try to take the first step and document the database interactions we have sometime soon.

I'd like to gradually reduce the complexity of FOQUS and try to make it somewhat maintainable.  There is a lot of weird stuff that was just a product of rushed development, and now maybe we can slowly fix it.

**Comment by ksbeattie** [comment]
We can re-open this if/when it becomes a higher priority.
