### ISSUE TITLE
Turbine: Unable to read dll or opt files

### ISSUE THREAD

**Issue by johnbaca** [CCSI-Toolset/FOQUS#436]
Turbine was not able to read the dll and opt files from the aspen model I was working with. I re-download foqus march 6, since I've been having troubles with turbine. I am using the visible options in the setting of the node to trouble shoot the problem. Turbine is not reading the fortran code within our model. I also keep receiving the following error message:

![image](https://user-images.githubusercontent.com/47044799/54043743-943f9d00-418a-11e9-99c4-2176c52e18d7.png)

**Comment by eslickj** [comment]
Did you upload the opt and dll files to TurbineLite?  Creates copies of the files when it runs them.  It needs those files in its database, so they get copied too.  I'm not sure how your simulation is set up either, but even if you do upload those files to turbine the relative location needs to be right.  Like if they are in a subdirectory of the aspen file location, you need that information too.

**Comment by CSRussell2319** [comment]
@eslickj John has tried uploading the files in Simsinter and within the turbine upload page. We're pretty sure that we're uploading to TurbineLite since FOQUS is fine running Aspen simulations that don't require dll files. In Aspen there's an opt file which specifies two dll files. The opt file has no directory listed in the Aspen simulation so it looks at the current path for it. The opt file lists no directory for the dll files so Aspen assumes they're also in the current path. John can post screenshots of the upload process if that would be useful.

**Comment by eslickj** [comment]
There is a test directory in the foqus working directory.  This is were turbine puts the simulations to run.  The directories in there are numbered by job.  You can look into one of the latest jobs and see if the files you need are in there.  If they seem to be right you can also try running those from Aspen and see if they run.

**Comment by johnbaca** [comment]
@eslickj I finally got it to work, It was missing a dll file that it needed to run. Thank you for the suggestion. I'm still working on getting familiar with Foqus and I appreciate all your help. There is no longer an issue.

**Comment by eslickj** [comment]
I think this is good will close.
