### ISSUE TITLE
Flowsheet data table functions

### ISSUE THREAD

**Issue by eslickj** [CCSI-Toolset/FOQUS#456]
It seems that delete rows doesn't work on the flowsheet data table.  Need to check all the data table functions and fix if necessary.

**Comment by ksbeattie** [comment]
@eslickj says the delete functionality was fixed in #458 but more testing is needed.

**Comment by fsoepyan** [comment]
- I tested the "Export" in the Menu for the Flowsheet data table
- I managed to generate the CSV file with the results
- I also managed to copy and paste the results into Excel
- The "Export" feature works!

**Comment by fsoepyan** [comment]
For the "Import" in the Menu for the Flowsheet data table:
- I managed to copy and paste the information from the the same CSV file that I generated when I tested the "Export" feature into the data table when I choose to "Import from CSV file"
- Then, I tried to copy and paste by copying a row from the CSV file with the numbers and other information (so that the number of items match the FOQUS data table)
- I got this error message when I choose "Paste data from clipboard":

![image](https://user-images.githubusercontent.com/30811140/56983623-1082ab00-6b52-11e9-968d-8e41e4a10ac9.png)

**Comment by fsoepyan** [comment]
- I selected a row in the Flowsheet data table
- I selected "Row to Flowsheet" under "Edit"
- I got this error message:

![image](https://user-images.githubusercontent.com/30811140/56984920-30679e00-6b55-11e9-87e4-106b639dfcd3.png)

**Comment by fsoepyan** [comment]
Under the "Edit" option:
- In the past, "Clear All Data" works
- I tested "Delete Rows", and this works
- I selected "Add Empty Result", and I got this error message:

![image](https://user-images.githubusercontent.com/30811140/56985090-8dfbea80-6b55-11e9-9fc7-de7ae746046f.png)

**Comment by fsoepyan** [comment]
Also under the "Edit" option, I tried "Edit Set for Selected Rows", I entered a new set name, and I got this error message:

![image](https://user-images.githubusercontent.com/30811140/56985167-b552b780-6b55-11e9-8406-7203c0c98f09.png)

**Comment by fsoepyan** [comment]
The "Calculated Columns" works fine.

**Comment by fsoepyan** [comment]
All items under the "View" option work fine.

**Comment by fsoepyan** [comment]
I selected a row, I selected "Run Selected Rows", and I got this error message:

![image](https://user-images.githubusercontent.com/30811140/56985527-8ee14c00-6b56-11e9-8987-6a52d97723a0.png)

**Comment by fsoepyan** [comment]
In summary, the errors occurred for the following items:
- "Run Selected Rows"
- The "Import" menu: "Paste data from clipboard"
- The "Edit" menu: "Row to Flowsheet", "Add Empty Result", and "Edit Set for Selected Rows"

**Comment by fsoepyan** [comment]
- This issue is not hindering FOQUS' main functions.
- For instance, the user can run a specified set of inputs from previous runs by putting the input variables' names and values into a CSV file, uploading the CSV file into UQ, and running the samples.
- Therefore, I will move this issue from medium to low priority.

**Comment by fsoepyan** [comment]
The "Row to Flowsheet" feature:

For example, if I select Row 98, and select "Row to Flowsheet", Row 97 ends up becoming the Flowsheet input (instead of Row 98).

This is a minor error, and can be fixed for the next release.

**Comment by fsoepyan** [comment]
Resolved with PR #510.
