### ISSUE TITLE
Running parallel simulation with FOQUS and process simulator on local machines

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#461]
We're wondering if we can perform parallel computing with FOQUS and a process simulator (Aspen Plus, ACM, and/or gPROMS) on a group of local machines.

What modifications do we need to make to FOQUS?

**Comment by eslickj** [comment]
With PR #470 it seems to work to run simulations in parallel by running multiple consumers on a single computer and setting FOQUS to remote.  I ran with two consumers, and the only problem I had was that it seems both consumers picked up the last job in the set, although it didn't seem to cause problems.  Otherwise it all seemed fine.  I'll have to look at how the consumers pick up jobs, but we may need to add some kind of lock for running multiple consumers on a single machine.

**Comment by fsoepyan** [comment]
Status update: please see #321.

**Comment by fsoepyan** [comment]
- As I mentioned in #321, I tested remote turbine today, and it works, with PR #470
- Can we close this issue, or is there more that we need to do?

**Comment by ksbeattie** [comment]
Closing this as the functionality works, documenting it will continue in #27
