### ISSUE TITLE
Heat Integration & Steam Cycle Plugin Model Issue

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#495]
While trying to implement the Heat Integration Tutorial in the Manual, i came across a few issues related to the source code. I tried to fix it stepwise, however, it has not been entirely fixed. Please find attached, a document explaining the issues, and the possible changes which i implemented to fix it. Kindly let me know your thoughts & suggestions. 

[Foqus_Heat_Integration_Issues.docx](https://github.com/CCSI-Toolset/FOQUS/files/3209100/Foqus_Heat_Integration_Issues.docx)

**Comment by eslickj** [comment]
The problem here is that heat integration relies on vector variables, which FOQUS doesn't support anymore.  It's not really possible to fix this in a simple way.  I think we either need to rework the heat integration module or remove it.  For the release we may want to remove the heat integration section from the docs, so no one attempts the tutorial.  The should be a sufficient temporary fix.

**Comment by ksbeattie** [comment]
Will leave this issue open to work on fixing heat integration for next release.

**Comment by anujad95** [comment]
The issue has been resolved
