### ISSUE TITLE
Reorganize example, testing and tutorial dir trees

### ISSUE THREAD

**Issue by ksbeattie** [CCSI-Toolset/FOQUS#558]
The existing structure is somewhat confusing and not well-understood, perhaps with unneeded, broken tests, etc.  We should clean this up, add readme.md files and re-organize it so it is more up-to-date and easier to understand.

Use this issue for making suggestions on exactly what to change.

**Comment by boverhof** [comment]
I propose
- examples/flowsheets/OUUByron/
-    examples/simulations/BFB/

**Comment by fsoepyan** [comment]
For the reorganization, I have an idea. Can we split the "examples" folder into 3 folders:
- tutorial_files
- test_files
- other_files

In these 3 folders, we can have subfolders that says "ALAMO", "Heat_Integration", "Optimization", etc.

I can put the BFB file that I use for OUU in the "test_files/OUU_BFB" folder.

What do you think?

**Comment by sotorrio1** [comment]
I like that idea. It would require some updates in the documentation to reflect the new paths, on LLNL side of things: 
/examples/tutorial_files/UQ
/examples/tutorial_files/OUU
/examples/tutorial_files/SDOE

**Comment by ksbeattie** [comment]
@fsoepyan will take a whack at this and open a PR with his proposed new org.

**Comment by fsoepyan** [comment]
I started on the reorganization, it is still a work in progress, but if you are interested, you can find it in my fork and branch: https://github.com/fsoepyan/FOQUS/tree/reorganization/examples

**Comment by fsoepyan** [comment]
So far, for the re-organization:
- For the examples/other_files folder, I only have 1 dummy file (I created this file so that I can create the "other_files" subfolder).
- For the examples/test_files folder, I have 1 subfolder that contains the 3 files for testing OUU in Remote Turbine.
- For the examples/tutorial_files folder, I have placed contents for following tutorials:
- [ ] Flowsheets and Settings
- [ ] Optimization
- [ ] Uncertainty Quantification
- [ ] Optimization Under Uncertainty
- [ ] Surrogate Modeling
- [ ] SDOE
- [ ] Simulation Standard Interface (SimSinter)
- [ ] Heat Integration
- [ ] PYOMO-FOQUS
