### ISSUE TITLE
Confidence level of FOQUS sessions

### ISSUE THREAD

**Issue by anujad95** [CCSI-Toolset/FOQUS#565]
In the "Session" tab of FOQUS there is an option to select among 3 confidence levels: "experimental", "testing" and "production". It would be helpful to know how FOQUS settings change for each of them, and whether examples at the "testing" and "production" level have been tried before. If not, we may want to make some modifications here.

**Comment by eslickj** [comment]
Those were for some data management framework integration.  They do nothing.  The idea was that they would keep track of models in the library, and if they were one or a work in progress.  We can change them any way you want or remove them.

**Comment by anujad95** [comment]
We can leave it as it is, if its just meant for keeping track of models in the library. Also, since these confidence levels are associated with scale of the process, do you see a possibility of including testing or production level examples in FOQUS? I'm not sure if such examples are there in the model library.

**Comment by eslickj** [comment]
There really isn't a model library.  I guess the idea was an organization would store models in a data management framework, that was part of CCSI.  The models would have some level of readiness associated with them.  This as that for FOQUS stuff stored in the DMF.  Since we sort of lost the DMF, I don't know that the confidence levels are all that meaningful any more.

**Comment by ksbeattie** [comment]
We'll leave this as it is for now.
