### ISSUE TITLE
Compatibility with Python 3.x

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#75]
We would like for FOQUS to be compatible with Python version 3.6 (i.e., the latest version of Python).

**Comment by eslickj** [comment]
I took a first pass at this partly manual editing and partly 2to3.  Moving forward we could probably move to Python 3.x and drop 2.7 support.  I created a new branch that hopefully we could eventually move to master, but we need to test it extensively.

Also to test this I have a hacked up copy of turb_client.  I can add a py3 branch to turb_client but @boverhof will probably want to convert that himself.

Let me know if anyone has any concerns about moving to Python 3.

**Comment by CSRussell2319** [comment]
Logistically what is the best way to go about this? Should we have a branch on the master fork that we push PR's to so that this project is independent of the master branch? I'm not familiar enough with 3.x vs 2.x backwards compatibility to know if we could break something on the 2.x side while working on this, but the branch structure I'm referring to is pretty common in other projects with multiple bases (ex Android or Linux).

I just saw @eslickj comment. I'll leave my text as is for reference. I suggest that we keep the 3.x build of Foqus on a separate branch and support them separately. I think that will reduce issues between the two.

**Comment by eslickj** [comment]
Supporting two branches is okay for a few weeks or a couple months, but we probably won't want two for very long.  Should we just drop support for Python 2.7 or should we make the py3 branch support both? Supporting both is probably only a minor inconvenience.  Another consideration is that PyQt5 isn't really supposed to have 2.7 packages, but apparently Anaconda provides them, so the 2.7 support is also tied to Anaconda.

**Comment by CSRussell2319** [comment]
@eslickj can I please have a copy of the "hacked together" version of turbine client for testing?

**Comment by eslickj** [comment]
@CSRussell2319, sorry I meant to put this up last week.  The py3 branch here should work well enough to make FOQUS run. https://github.com/eslickj/turb_client

I'm slowly working through your tests.  The most common problem I'm seeing is from Python 3 not automatically converting between bytes and strings, so there is probably a lot of debugging work to do.

**Comment by ksbeattie** [comment]
This is blocked by #334

**Comment by eslickj** [comment]
I think this is now done enough to close this and open new issues if they come up in testing.
