### ISSUE TITLE
OUU: Multi-Objective Optimization

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#76]
We would like to add the multiple-objective optimization capability to FOQUS.

**Comment by ksbeattie** [comment]
I'm placing this on the July board, but it might not be done by then, which is ok.

**Comment by ksbeattie** [comment]
@sotorrio1 says this is in progress and might have something new for it soon...

**Comment by ksbeattie** [comment]
@sotorrio1 says he has something nearly working.

**Comment by ksbeattie** [comment]
@ngbrenda says it works but there are performance issues.  pygmo is used for MOUU, whereas psuade is used for OUU.  Trying to keep the interface similar across the two is creating a lot of slow I/O.

**Comment by anujad95** [comment]
What is the current status of this capability in FOQUS?

**Comment by sotorrio1** [comment]
The development of MOOUU is on standby since we focused our efforts on SDoE. Once we deliver the next phase of SDoE we should be able to go back to working on the multi-objective capability.

**Comment by anujad95** [comment]
Sure, no problem.

**Comment by sotorrio1** [comment]
The Multi-Objective Optimization Under Uncertainty (MOOUU) feature is still on stand-by since we're trying to decide which path to follow. 

- Adding multi-objective capabilities to the existing OUU tab using an open source python library. The single objective would stay the same using PSUADE. 

OR 

- Completely re-factor the OUU module, moving away from PSUADE and using the open source multi-objetive library. This way there would be less I/O writing, making the process more efficient and faster.
