### ISSUE TITLE
Error when importing PyQt5.QtWidgets

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#821]
There is an error while loading foqus in the foqus.py file when it's trying to load PyQt5.QtWidgets

**Comment by lbianchi-lbl** [comment]
I think I've managed to find a minimal example that reproduces this behavior.

1. Activate the virtual/Conda environment, e.g. `source activate my-foqus-env` or `conda activate my-foqus-env`
1. Run the following commands:
  - **A**: `python -c 'import PyQt5; print(PyQt5.QtWidgets.QApplication([]))'`
  - **B**: `python -c 'from PyQt5 import QtWidgets; print(QtWidgets.QApplication([]))'`
  - **C**: `foqus`

On my system,

-  **A** results in the same error as originally reported for this issue:
    ```txt
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: module 'PyQt5' has no attribute 'QtWidgets'
    ```
- **B** does not cause an error and displays the repr of the `QApplication` object as expected:
    ```txt
    <PyQt5.QtWidgets.QApplication object at 0x7f1ee5a6aa50>
    ```
- **C** does not cause an error, and the FOQUS GUI appears as expected

I'm quite confused by these results:

- **A** is (a simplified version of) how the GUI is loaded in the `foqus` entry point **C**, but **C** works while **A** doesn't
- Naively, one would expect **A** and **B** to be equivalent, but **A** results in the error, while **B** doesn't

In my experience, PyQt's behavior can vary quite a lot depending not only on the version and how it is installed (pip, Conda), but also on the operating system. To help gather more information when running the tests above, run these commands from the same active environment:

- **D1**: `conda list --revisions`
- **D2**: `python -m pip list`
- **D3**: `python -c 'import platform as p; print(p.platform())`

**Comment by lbianchi-lbl** [comment]
I've tried an additional test snippet: it is the same as **A**, but running the import from `foqus_lib.framework.session.session` first, as it happens in `foqus_lib.foqus.main()`:

- **D**: `python -c 'from foqus_lib.framework.session.session import *; import PyQt5; print(PyQt5.QtWidgets.QApplication([]))'`

Unlike **A**, this runs without errors.

My hypothesis is that PyQt5 has some form of lazy import mechanism:

- (some of) its submodules are not imported automatically when running `import PyQt5`, but must be imported directly first, e.g. `from PyQt5 import QtWidgets`
  - This would explain why **A** doesn't work while **B** does
- Once the import has taken place (module imports are run only once and then cached), they will be accessible from `PyQt5` without issues
  - This would explain why **D** works when **A** doesn't, since `foqus_lib.framework.session.session` itself imports a large number of other modules, which at some point of the chain will result in PyQt5 modules being imported *à la* **B**

However, it's still not clear to me why the original error (which is basically **C** resulting in the same error as **A**) occurs: from the code in `foqus_lib.foqus`, the imports run before the `guiImport()` function is called, and so I would expect **C** to succeed for the same reason that **D** does. Hopefully these simpler code snippets will help narrowing down the conditions in which the error occurs.

**Comment by sotorrio1** [comment]
Alright so on my system, macOS Catalina 10.15.6:

`conda list --revisions`:

``` txt
2020-08-13 14:29:26  (rev 0)
    +ca-certificates-2020.6.24 (defaults/osx-64)
    +certifi-2020.6.20 (defaults/osx-64)
    +libcxx-10.0.0 (defaults/osx-64)
    +libedit-3.1.20191231 (defaults/osx-64)
    +libffi-3.3 (defaults/osx-64)
    +ncurses-6.2 (defaults/osx-64)
    +openssl-1.1.1g (defaults/osx-64)
    +pip-20.2.2 (defaults/osx-64)
    +python-3.7.7 (defaults/osx-64)
    +readline-8.0 (defaults/osx-64)
    +setuptools-49.2.0 (defaults/osx-64)
    +sqlite-3.32.3 (defaults/osx-64)
    +tk-8.6.10 (defaults/osx-64)
    +wheel-0.34.2 (defaults/osx-64)
    +xz-5.2.5 (defaults/osx-64)
    +zlib-1.2.11 (defaults/osx-64)
```

`python -m pip list`:

``` txt
Package         Version             Location
--------------- ------------------- -----------------------------------------------
boto3           1.14.42
botocore        1.17.42
ccsi-foqus      3.7.0.dev0          /Users/sotorrio1/PycharmProjects/FOQUS-sotorrio
certifi         2020.6.20
chardet         3.0.4
cma             3.0.3
cycler          0.10.0
decorator       4.4.2
docutils        0.15.2
idna            2.10
jmespath        0.10.0
joblib          0.16.0
kiwisolver      1.2.0
matplotlib      3.3.0
mlrose-hiive    2.1.3
mplcursors      0.3
networkx        2.4
numpy           1.19.1
pandas          1.1.0
Pillow          7.2.0
pip             20.2.2
psutil          5.7.2
pyparsing       2.4.7
PyQt5           5.13.0
PyQt5-sip       12.8.0
python-dateutil 2.8.1
pytz            2020.1
requests        2.24.0
s3transfer      0.3.3
scikit-learn    0.23.2
scipy           1.5.2
setuptools      49.2.0.post20200714
six             1.15.0
threadpoolctl   2.1.0
tqdm            4.48.2
TurbineClient   3.1.0
urllib3         1.25.10
wheel           0.34.2
```

`python -c 'import platform; print(platform.uname())`:

``` txt
uname_result(system='Darwin', node='ml-9775914.llnl.gov', release='19.6.0', version='Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64', machine='x86_64', processor='i386')
```

An then results for the tests:

- A: `python -c 'import PyQt5; print(PyQt5.QtWidgets.QApplication([]))'`
``` txt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'PyQt5' has no attribute 'QtWidgets'
```

- B: `python -c 'from PyQt5 import QtWidgets; print(QtWidgets.QApplication([]))'`
```txt
<PyQt5.QtWidgets.QApplication object at 0x7ffdc80bb9b0>
```

- C: `foqus`: No error, FOQUS GUI opens
