### ISSUE TITLE
OUU: problem with regex on Windows

### ISSUE THREAD

**Issue by sotorrio1** [CCSI-Toolset/FOQUS#843]
When running OUU on Windows, the plot updating triggers a regex error. See below:

![Screen Shot 2020-10-29 at 11 34 03 AM](https://user-images.githubusercontent.com/33531919/97622994-42dcc500-19e2-11eb-8f79-9cd77118841f.png)

**Comment by lbianchi-lbl** [comment]
@sotorrio1 Thanks for reporting this issue. As discussed in https://github.com/CCSI-Toolset/FOQUS/pull/834#issuecomment-718965061, during the testing of which this was encountered, I believe this is partly (but not only) due to the fact that new lines in Windows are `\r\n`, as opposed to simply `\n` for other OSes.
Another possible cause of error is the fact that, if the text being parsed here contains numbers written in scientific notation (e.g. `2.5e-1`), the regex pattern must be capable of dealing with this (e.g. `[0-9]*` would not extract the complete number).

Would it be possible to get a sample of the text being parsed, that was generated on Windows? (possibly even the very same text that resulted in the error being reported).

From that, I'd probably start by debugging the regex using https://regex101.com/ (after selecting "Python" in the "Flavor" box on the left).

**Comment by lbianchi-lbl** [comment]
From a quick check it's possible that `strip()`ping the string before parsing it could help:

```py
>>> import re
>>> pat = 'Current Level 1 input \s*[0-9]* = (.*)'
>>> s = 'Current Level 1 input   1 = -3.178523e-02\r\n'
>>> re.findall(pat, s)
['-3.178523e-02\r']
>>> re.findall(pat, s.strip())
['-3.178523e-02']
```
However, I don't think this alone would fully account for the issue: the parsed string is `2.053804e\r`, which means that the rest of the number after the `e` is not captured by the regex.

As this could be due to unexpected variations in the input format, I think that looking at the parsed text that caused the issue would be the most direct way of knowing more about this.

**Comment by lbianchi-lbl** [comment]
- The fact that this issue occurred while testing #834 might or might not be caused specifically by the changes introduced there (switching from BAT file to Python entry point executable)
- @sotorrio1 will test again and, if possible, provide a sample of the output causing the parsing issue
- Long term, there is interest in more robust solutions for the interaction between FOQUS and PSUADE, such as e.g. machine-readable input/output that would not require parsing on FOQUS's side

**Comment by sotorrio1** [comment]
This is no longer an issue
