### ISSUE TITLE
Optimization: changing orders of variables in "Variables" tab and different sample sizes for variables in "Samples" tab

### ISSUE THREAD

**Issue by puttak** [CCSI-Toolset/FOQUS#89]
1. Under Optimization tab, in variables sub-tab, it would be helpful, if we have the ability to move the variables up and down, so that the user can group the variables related particular type of data.

2. The user cannot perform Optimization using different types data with different sizes. In general, especially for Carbon-capture the experimental data for sub-models development is always of different size. Now the user must make dummy-cases so that they can have same size

**Comment by fsoepyan** [comment]
Regarding the 2nd comment:
- For the optimization, FOQUS can now do a full factorial for the samples, and the sizes of the samples do not need to be the same.
- For instance, suppose I have variables x1 and x2 that I specified as samples.
- The values of x1 are 2, 3, 4.
- The values of x2 are 8 and 9.
- With the full factorial feature, FOQUS will automatically combine the samples, so that the sample points are (x1, x2) = (2, 8), (2, 9), (3, 8), (3, 9), (4, 8), and (4, 9).

**Comment by eslickj** [comment]
The second comment is probably a misunderstanding and I'm not going to implement the first thing.
