### ISSUE TITLE
SDoE UX: Investigate window stack ordering after closing a plot

### ISSUE THREAD

**Issue by sspoon** [CCSI-Toolset/FOQUS#978]
This might be specific to a person's environment, but it appears that closing a plot in the SDoE module causes the order of FOQUS window stack to change in an unexpected way. Specifically, the main FOQUS window will appear on the top of the stack instead of the last window opened. This was first reported by Abby, and I was also able to replicate this type of behavior. 

For example, the first window in the SDoE module is the main FOQUS window (1):
<img width="1258" alt="Screen Shot 2021-11-08 at 12 00 25 PM" src="https://user-images.githubusercontent.com/5075865/140812186-66e55fc9-5d1b-40ab-b75a-d986d9cffebc.png">

After uploading a candidate set and clicking on the "Open SDoE Dialog" button, you will get a experiment setup window (2):
<img width="1436" alt="Screen Shot 2021-11-08 at 12 01 01 PM" src="https://user-images.githubusercontent.com/5075865/140812389-c10822bc-c3c6-4240-a405-c4afbb43a884.png">

Once the experiment is run, click on the "view" button on one of the designs and the design input preview (3):
<img width="1404" alt="Screen Shot 2021-11-08 at 12 01 57 PM" src="https://user-images.githubusercontent.com/5075865/140812534-5cf6e7c7-800f-48ce-9624-8441995037b8.png">

Finally plot the design (4):
<img width="1435" alt="Screen Shot 2021-11-08 at 12 02 22 PM" src="https://user-images.githubusercontent.com/5075865/140812611-8a94e006-041d-4572-b68e-ea6f560e7cce.png">

Now when you close the plot window, window 1 (the main FOQUS window) will pop to the top of the window stack, when you are expecting to be in state 3 (small window with input preview).
<img width="1424" alt="Screen Shot 2021-11-08 at 12 02 35 PM" src="https://user-images.githubusercontent.com/5075865/140812919-e76b3f7d-7d87-4857-8734-58af828dfbf7.png">

Again, this might be specific to the user environment. I am running on a mac.

**Comment by sotorrio1** [comment]
@sspoon I experience this in a Mac as well but not in Windows. A while back I remember trying to track this down and fixing it with different settings with no success...

**Comment by sspoon** [comment]
@sotorrio1 Yes, I figured it might be specific to the operating system. I'm not sure if perhaps @lbianchi-lbl might have some ideas, but otherwise, we might not be able to do anything about this one.

**Comment by lbianchi-lbl** [comment]
- I've looked into this a bit and I was able to confirm this on my Linux machine (Ubuntu, although with a non-default window manager that may or may not impact the result)
- From looking at the code, I think that the reason for this is because the plots are shown in a window generated by matplotlib/pyplot when calling `plt.show()` in `foqus_lib.framework.sdoe.plot_utils.plot()`
- This is different from the "stack" of dialogs created by calling the `exec_()` and/or `show()` methods of `QDialog` and subclasses, which might account for the fact that, when the window with the plot is closed, the focus goes back to the main window instead of the latest dialog at the top of the stack
- I've also tried to find a way to somehow "force" the window with the plots to "play nice" with the dialogs following several of the workarounds suggested [here](https://stackoverflow.com/questions/8202228/make-matplotlib-plotting-window-pop-up-as-the-active-one), but unfortunately without much success

**Comment by sotorrio1** [comment]
@lbianchi-lbl thanks for looking into this. Perhaps there is a way we can show the plot on a QDialog instead of a matplotlib window?

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl thanks for looking into this. Perhaps there is a way we can show the plot on a QDialog instead of a matplotlib window?

Yeah, I agree that this sounds like something that should be possible in some way. I don't have much experience with matplotlib + Qt though, so I'd have to look this up.

**Comment by eslickj** [comment]
It's been several years, so I don't recall the details, but optimization has an example of putting matplotlib plots in a normal QT widget instead of a new matplotlib window.  These plots are updated as the optimization runs, so it's probably a little extra complicated. 

https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/optimization/optMonitor.py

**Comment by lbianchi-lbl** [comment]
> It's been several years, so I don't recall the details, but optimization has an example of putting matplotlib plots in a normal QT widget instead of a new matplotlib window. These plots are updated as the optimization runs, so it's probably a little extra complicated.
> 
> https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/optimization/optMonitor.py

Thanks @eslickj, I think your solution should work well for this use case. @sotorrio1 As I understand, the `FigureCanvas` from the `qtagg` backend is a `QWidget` subclass, so it can be added to any normal `QWindow`/`QDialog` as normal. At that point we'd just need to create the plot "manually" by:

- Instantiating a `Figure` object (https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/optimization/optMonitor.py#L78-L98)
- Configuring the plot layout (https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/optimization/optMonitor.py#L152-L174)
- Setting or updating the data for the plots using the relevant `Axes` objects (https://github.com/CCSI-Toolset/FOQUS/blob/master/foqus_lib/gui/optimization/optMonitor.py#L250-L255)

**Comment by lbianchi-lbl** [comment]
@sotorrio1 and I investigated the issue in more detail and seems to be connected to the usage of `matplotlib.pyplot.show()` and the `qt5agg` matplotlib backend:

- Running a Qt-based backend within a Qt app causes some kind of conflict (`QCoreApplication::exec: The event loop is already running` is emitted by the current implementation and visible in the terminal output)
- Simply switching to a different backend doesn't seem to be working (`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt' is currently running`)
- I'm currently working to see if it's possible to e.g. implement a custom "wrapper" backend that collects the figures and adds them to an existing widget within the FOQUS QApplication instance without requiring any change in the SDoE `plot_utils` code
- A more robust solution long-term would be to modify `plot_utils` so that `Figure` objects are returned by the plot-generating functions and then added to the widget within the SDoE GUI calling code (instead of having to rely on the `pyplot.show()` global function to display them)
